services:
  - type: web
    name: zebra-ocr-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
    startCommand: python app.py
